# Generated by Django 4.2.29 on 2026-03-17 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('thumbnail_url', models.URLField()),
                ('video_url', models.URLField()),
                ('duration', models.IntegerField()),
                ('release_date', models.DateField()),
                ('is_trending', models.BooleanField(default=False)),
            ],
        ),
    ]
